/**
 * Libellés UX critiques — Mobile PulsePanel
 * Vocabulaire cohérent : gains, solde, retrait, erreurs.
 */

export const wallet = {
  title: "Portefeuille",
  pendingLabel: "En attente",
  pendingHint: "Gains en cours de validation (réponses récentes)",
  availableLabel: "Disponible",
  availableHint: "Montant que vous pouvez demander en retrait",
  totalLabel: "Total",
  totalEarnedLabel: "Total gagné",
  sectionRetrait: "RETRAIT",
  ctaContinueResponding: "Continuer à répondre",
  heroSubtextPendingOnly: "En attente de validation",
  heroSubtextMinWithdraw: "Min. 5 € pour retirer",
  heroSubtextRemaining: "avant de pouvoir retirer",
  withdrawTitle: "Demander un retrait",
  withdrawButton: "Demander un retrait",
  withdrawSending: "Envoi…",
  withdrawSuccess: "Demande enregistrée. Elle apparaîtra dans « Mes retraits ».",
  withdrawMinAmount: "Montant minimum : 5,00 €",
  withdrawInsufficient: "Solde insuffisant",
  withdrawFrozen: "Les retraits sont temporairement indisponibles pour ce compte. Contacte le support si nécessaire.",
  withdrawDailyLimit: "Tu as déjà atteint la limite de demandes de retrait pour aujourd'hui.",
  withdrawGenericError: "Impossible de demander le retrait. Réessayez plus tard.",
  withdrawHintMin: "Montant minimum de retrait : 5 €. Rechargez en répondant à des campagnes.",
  historyTitle: "Historique",
  activitySummaryTitle: "Résumé activité",
  todayLabel: "Aujourd'hui",
  thisWeekLabel: "Cette semaine",
  thisMonthLabel: "Ce mois",
  summaryToday: "Aujourd'hui",
  summaryWeek: "Semaine",
  summaryMonth: "Mois",
  activityRecentTitle: "Activité récente",
  filterAll: "Tous",
  filterAvailable: "Disponibles",
  filterPending: "En attente",
  filterEmpty: "Aucune entrée pour ce filtre.",
  seeMoreHistory: "Voir plus",
  myWithdrawalsTitle: "Mes retraits",
  emptyHistory: "Aucune réponse pour l'instant.",
  emptyHistorySubtext: "Répondez à des questions pour faire apparaître vos gains ici.",
  emptyHistoryCta: "Répondre pour gagner",
  emptyWithdrawals: "Aucun retrait pour l'instant.",
  noBalanceBanner: "Répondez à une campagne pour voir votre solde ici.",
  statusPending: "En attente",
  statusAvailable: "Disponible",
  statusPaid: "Payé",
  statusRejected: "Refusé",
  olderLabel: "Plus ancien",
  quickActionRefresh: "Rafraîchir",
  quickActionFeed: "Voir le feed",
  heroActivityCount: "réponses récentes",
  activityCountLine: "réponses",
} as const;

export const feed = {
  title: "Feed",
  loadingCampaigns: "Chargement des campagnes…",
  emptyLoadError: "Impossible de charger les campagnes.",
  emptyNoCampaigns: "Aucune campagne disponible pour le moment.",
  emptyMock: "Plus de questions pour l'instant.",
  /** Affiché quand le backend n'est pas configuré : pas de fausses campagnes. */
  emptyNoBackend: "Aucune campagne. Connectez l'app au backend pour afficher les campagnes réelles.",
  emptySubNoBackend: "En mode démo sans backend, les campagnes s'afficheront une fois l'app connectée.",
  emptySubError: "Vérifiez votre connexion et réessayez.",
  emptySubDefault: "Revenez plus tard pour gagner des récompenses.",
} as const;

export const answer = {
  submitSending: "Envoi…",
  submitErrorDefault: "Impossible d'enregistrer la réponse. Réessayez.",
} as const;

export const profile = {
  title: "Profil",
  sectionAccount: "Compte",
  sectionTargeting: "Ciblage",
  sectionNotifications: "Notifications",
  sectionLocation: "Localisation",
  sectionStats: "Statistiques",
  displayNameLabel: "Nom affiché",
  displayNamePlaceholder: "Votre prénom ou pseudo",
  emailLabel: "Email",
  emailAnonymous: "Compte invité",
  trustLabel: "Niveau de confiance",
  trustHint: "Mis à jour selon la qualité des réponses",
  ageLabel: "Tranche d'âge",
  regionLabel: "Région / Département",
  interestsLabel: "Centres d'intérêt",
  notifGlobal: "Activer les notifications",
  notifNewCampaigns: "Nouvelles campagnes",
  notifWallet: "Gains et portefeuille",
  notifReminders: "Rappels",
  locationToggle: "Utiliser ma localisation",
  locationHint: "Pour vous proposer des campagnes proches de vous. Uniquement à la demande, pas de suivi permanent.",
  locationEnabled: "Localisation activée",
  locationCity: "Ville",
  completeProfileTitle: "Complétez votre profil",
  completeProfileBody: "Ajoutez un nom et vérifiez vos préférences pour des campagnes mieux ciblées.",
  save: "Enregistrer",
  edit: "Modifier",
  heroSheetTitle: "Mon compte",
  heroSheetPhotoLabel: "Photo de profil",
  heroSheetPhotoHint: "Bientôt : ajout d'une photo. Pour l'instant, vos initiales sont affichées.",
  badgeSectionTitle: "Niveau de confiance",
  badgeBronzeExplanation: "Bronze est le premier niveau. Il reflète votre début sur PulsePanel et la régularité de vos réponses.",
  badgeScoreExplanation: "Le score mesure la qualité et la régularité de votre participation. Plus vous répondez de façon pertinente, plus il progresse.",
  badgeProgressExplanation: "Pour progresser : répondez régulièrement et avec soin aux campagnes. Les niveaux Argent puis Or débloquent davantage de campagnes et de récompenses.",
  ciblageHint: "Ces informations nous aident à vous proposer des campagnes plus pertinentes.",
  emailVerified: "Email vérifié",
  emailNotVerified: "Email non vérifié",
  notifStatusEnabled: "Activées",
  notifStatusDenied: "Refusées",
  notifStatusUnavailable: "Indisponibles",
  notifUnavailableHint: "Les notifications ne sont pas disponibles sur cet environnement (Expo Go ou simulateur). Utilisez une build native pour les activer.",
  notifDeniedHint: "Pour recevoir les rappels et les alertes, autorisez les notifications dans les réglages.",
  notifOpenSettings: "Ouvrir les réglages",
  locationUpdate: "Mettre à jour la position",
  photoChange: "Changer la photo",
  photoRemove: "Supprimer la photo",
  sectionAccountSupport: "Compte et support",
  rowMonCompte: "Mon compte",
  rowAideSupport: "Aide et support",
  rowConfidentialite: "Confidentialité et localisation",
  rowDeconnexion: "Déconnexion",
  rowDemanderSuppression: "Demander la suppression du compte",
  rowMentions: "Mentions légales",
  rowVersion: "Version",
  deleteAccountPlaceholder: "Contacter le support pour demander la suppression de votre compte.",
  helpPlaceholder: "Une question ? Contactez-nous via l'app ou par email.",
} as const;
